version: "3.3"
services:
  pg:
    image: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cart_service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=cart1234
