version: "3.3"
services:
  pg:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=user_service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=user1234
